#!/usr/bin/env python3
"""Generate the Uno's safety constants from the canonical joints YAML."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "ros2" / "robo_arm_driver"))

from robo_arm_driver.config import load_arm_config  # noqa: E402


def _array(values) -> str:
    return "{" + ", ".join(values) + "}"


def render(config) -> str:
    calibrated = "true" if config.calibrated else "false"
    pins = _array(str(joint.servo_pin) for joint in config.joints)
    minimums = _array(f"{joint.min_deg:.2f}f" for joint in config.joints)
    maximums = _array(f"{joint.max_deg:.2f}f" for joint in config.joints)
    homes = _array(f"{joint.home_deg:.2f}f" for joint in config.joints)
    steps = _array(
        f"{joint.max_velocity_deg_s / config.control_rate_hz:.4f}f"
        for joint in config.joints)
    grip_min = min(config.gripper.open_percent, config.gripper.closed_percent)
    grip_max = max(config.gripper.open_percent, config.gripper.closed_percent)
    grip_step = config.gripper.max_velocity_percent_s / config.control_rate_hz
    tick_ms = round(1000.0 / config.control_rate_hz)
    return f"""// GENERATED by hardware/generate_firmware_config.py.
// Source: ros2/robo_arm_driver/config/joints.yaml
// Do not edit this header by hand; edit the YAML and run `make config`.
#pragma once

const bool ARM_CALIBRATED = {calibrated};
const uint8_t NJOINTS = 6;
const uint8_t SERVO_PIN[NJOINTS] = {pins};
const uint8_t GRIPPER_PIN = {config.gripper.servo_pin};
const float JMIN[NJOINTS] = {minimums};
const float JMAX[NJOINTS] = {maximums};
const float HOME_DEG[NJOINTS] = {homes};
const float MAX_STEP_DEG[NJOINTS] = {steps};
const float GMIN = {grip_min:.2f}f;
const float GMAX = {grip_max:.2f}f;
const float GHOME = {config.gripper.open_percent:.2f}f;
const float GMAX_STEP = {grip_step:.4f}f;
const uint16_t TICK_MS = {tick_ms};
const unsigned long COMMAND_TIMEOUT_MS = {config.command_timeout_ms}UL;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        default=ROOT / "ros2" / "robo_arm_driver" / "config" / "joints.yaml",
        type=Path,
    )
    parser.add_argument(
        "--output",
        default=ROOT / "hardware" / "firmware" / "arm_firmware" / "arm_config.h",
        type=Path,
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(load_arm_config(args.config))
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if actual != expected:
            print(f"stale firmware config: run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"firmware config matches {args.config}")
        return 0
    args.output.write_text(expected, encoding="utf-8")
    print(f"wrote {args.output} from {args.config}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
