// GENERATED by hardware/generate_firmware_config.py.
// Source: ros2/robo_arm_driver/config/joints.yaml
// Do not edit this header by hand; edit the YAML and run `make config`.
#pragma once

const bool ARM_CALIBRATED = false;
const uint8_t NJOINTS = 6;
const uint8_t SERVO_PIN[NJOINTS] = {3, 5, 6, 9, 10, 11};
const uint8_t GRIPPER_PIN = 4;
const float JMIN[NJOINTS] = {85.00f, 85.00f, 85.00f, 85.00f, 85.00f, 85.00f};
const float JMAX[NJOINTS] = {95.00f, 95.00f, 95.00f, 95.00f, 95.00f, 95.00f};
const float HOME_DEG[NJOINTS] = {90.00f, 90.00f, 90.00f, 90.00f, 90.00f, 90.00f};
const float MAX_STEP_DEG[NJOINTS] = {1.0000f, 1.0000f, 1.0000f, 1.0000f, 1.0000f, 1.0000f};
const float GMIN = 45.00f;
const float GMAX = 55.00f;
const float GHOME = 45.00f;
const float GMAX_STEP = 1.0000f;
const uint16_t TICK_MS = 50;
const unsigned long COMMAND_TIMEOUT_MS = 750UL;
